hirise:
  samples: 100
  host: "https://www.uahirise.org/PDS"

gdal:
  resampling: "bilinear"
  dem_nodata: -32767.0
  source_path: "datasets"
  driver: "COG"
  compressor_dem: "DEFLATE"
  compressor_mono: "DEFLATE"
  blocksize: 512 # 512, 1024
  overview_method: "BILINEAR"
  gdal_cache: 6144
  num_threads: "ALL_CPUS"
  predictor_dem: 2
